phpfpm:
  restart: always
  build: ./docker-php7full
#  image: php:5.6.17-fpm
  volumes:
    - ./php-fpm-7/fpm-conf:/usr/local/etc
    - ./php-fpm-7/ini:/usr/local/etc/php
    - ./app:/var/www/html
    - ./log/php-fpm:/var/log/php-fpm
  links:
    - db:db
    - es:es

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx

db:
  container_name: db
  image: mysql:5.6.27
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_HOST=db
    - MYSQL_DATABASE=pampam
    - MYSQL_USER=lukas
    - MYSQL_PASSWORD=lukas
  volumes:
    - ./mysql/script/:/script:rw
    - ./log/mysql:/var/log/mysql
    - ./mysql/databases:/var/lib/mysql
  command: "/script/permissions.sh"

pma:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:8080"
  links:
    - db:db
  environment:
    - PMA_HOST=db
    - PMA_USER=root
    - PMA_PASSWORD=root

es:
#  image: elasticsearch:2.1.1
  image: elasticsearch:1.7.4
  ports:
    - "9200:9200"
  volumes:
    - ./es:/usr/share/elasticsearch/data
    - ./es/script/:/script:rw
    - ./log/es:/var/log/elasticsearch
  command: "/script/permissions.sh"
